#!/bin/sh
# Portable Bootstrap Bundle Installer
# Generated by mksfx
# No magic. No implicit execution. Pure Unix.

set -e

EMBEDDED_CHECKSUM="PLACEHOLDER"
DESTDIR="${DESTDIR:-.}"
PAYLOAD_ARCHIVE="payload.tar.gz"
PAYLOAD_DIR="payload"
FORCE_EXTRACT=0

# Colors for output
if [ -t 1 ]; then
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  BLUE='\033[0;34m'
  NC='\033[0m'
else
  RED=''
  GREEN=''
  YELLOW=''
  BLUE=''
  NC=''
fi

log_info() {
  printf "${BLUE}ℹ${NC} %s\n" "$1"
}

log_success() {
  printf "${GREEN}✓${NC} %s\n" "$1"
}

log_error() {
  printf "${RED}✗${NC} %s\n" "$1" >&2
}

log_warn() {
  printf "${YELLOW}⚠${NC} %s\n" "$1"
}

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Portable Bootstrap Bundle Installer

OPTIONS:
  -v, --verify    Verify payload checksum
  -x, --extract   Extract payload to ./payload
  -r, --run       Execute bootstrap.sh (requires confirmation)
  -m, --menu      Interactive menu (default)
  -f, --force     Force overwrite on extract
  -h, --help      Show this help

ENVIRONMENT:
  DESTDIR         Extraction directory (default: .)

EXAMPLES:
  $(basename "$0") -v              # Verify only
  $(basename "$0") -x              # Extract only
  $(basename "$0") -v -x           # Verify then extract
  $(basename "$0") -v -x -r        # Full install with run
  DESTDIR=/opt $(basename "$0") -x # Extract to /opt/payload

EOF
}

detect_checksum_tool() {
  if command -v sha256sum >/dev/null 2>&1; then
    echo "sha256sum"
  elif command -v shasum >/dev/null 2>&1; then
    echo "shasum"
  else
    log_error "No checksum tool found (need sha256sum or shasum)"
    exit 1
  fi
}

calculate_checksum() {
  local file="$1"
  local tool=$(detect_checksum_tool)
  
  case "$tool" in
    sha256sum)
      sha256sum "$file" | awk '{print $1}'
      ;;
    shasum)
      shasum -a 256 "$file" | awk '{print $1}'
      ;;
  esac
}

verify_payload() {
  log_info "Verifying payload checksum..."
  
  if [ ! -f "$PAYLOAD_ARCHIVE" ]; then
    log_error "Payload archive not found: $PAYLOAD_ARCHIVE"
    log_info "Current directory: $(pwd)"
    log_info "Run from bundle directory (same dir as installer.sh)"
    exit 1
  fi
  
  local calculated=$(calculate_checksum "$PAYLOAD_ARCHIVE")
  
  if [ "$calculated" = "$EMBEDDED_CHECKSUM" ]; then
    log_success "Checksum verified: $calculated"
    return 0
  else
    log_error "Checksum mismatch!"
    log_error "  Expected: $EMBEDDED_CHECKSUM"
    log_error "  Got:      $calculated"
    exit 1
  fi
}

extract_payload() {
  log_info "Extracting payload..."
  
  if [ ! -f "$PAYLOAD_ARCHIVE" ]; then
    log_error "Payload archive not found: $PAYLOAD_ARCHIVE"
    exit 1
  fi
  
  local extract_path="${DESTDIR}/${PAYLOAD_DIR}"
  
  if [ -d "$extract_path" ] && [ "$FORCE_EXTRACT" -eq 0 ]; then
    log_error "Payload directory already exists: $extract_path"
    log_info "Use --force to overwrite"
    exit 1
  fi
  
  if [ "$FORCE_EXTRACT" -eq 1 ] && [ -d "$extract_path" ]; then
    log_warn "Removing existing payload directory..."
    rm -rf "$extract_path"
  fi
  
  mkdir -p "$DESTDIR"
  tar -xzf "$PAYLOAD_ARCHIVE" -C "$DESTDIR"
  
  log_success "Extracted to: $extract_path"
  
  # Show manifest
  if [ -f "${extract_path}/MANIFEST" ]; then
    log_info "Manifest:"
    sed 's/^/    /' "${extract_path}/MANIFEST"
  fi
}

run_bootstrap() {
  local bootstrap_path="${DESTDIR}/${PAYLOAD_DIR}/bootstrap.sh"
  
  if [ ! -f "$bootstrap_path" ]; then
    log_error "Bootstrap script not found: $bootstrap_path"
    log_info "Extract payload first with --extract"
    exit 1
  fi
  
  log_warn "About to execute: $bootstrap_path"
  printf "Continue? [y/N] "
  read -r response
  
  case "$response" in
    [yY][eE][sS]|[yY])
      log_info "Executing bootstrap..."
      sh "$bootstrap_path"
      ;;
    *)
      log_info "Bootstrap execution cancelled"
      exit 0
      ;;
  esac
}

interactive_menu() {
  while true; do
    echo ""
    echo "╔════════════════════════════════════════╗"
    echo "║  Bootstrap Bundle Interactive Menu    ║"
    echo "╚════════════════════════════════════════╝"
    echo ""
    echo "  1) Verify checksum"
    echo "  2) Extract payload"
    echo "  3) Run bootstrap"
    echo "  4) Verify + Extract"
    echo "  5) Verify + Extract + Run"
    echo "  6) Show manifest"
    echo "  0) Exit"
    echo ""
    printf "Select option: "
    read -r option
    
    case "$option" in
      1)
        verify_payload
        ;;
      2)
        extract_payload
        ;;
      3)
        run_bootstrap
        ;;
      4)
        verify_payload
        extract_payload
        ;;
      5)
        verify_payload
        extract_payload
        run_bootstrap
        ;;
      6)
        if [ -f "${DESTDIR}/${PAYLOAD_DIR}/MANIFEST" ]; then
          cat "${DESTDIR}/${PAYLOAD_DIR}/MANIFEST"
        else
          log_error "MANIFEST not found. Extract payload first."
        fi
        ;;
      0)
        log_info "Exiting"
        exit 0
        ;;
      *)
        log_error "Invalid option"
        ;;
    esac
  done
}

# Parse arguments
DO_VERIFY=0
DO_EXTRACT=0
DO_RUN=0
DO_MENU=0

if [ $# -eq 0 ]; then
  DO_MENU=1
fi

while [ $# -gt 0 ]; do
  case "$1" in
    -v|--verify)
      DO_VERIFY=1
      ;;
    -x|--extract)
      DO_EXTRACT=1
      ;;
    -r|--run)
      DO_RUN=1
      ;;
    -m|--menu)
      DO_MENU=1
      ;;
    -f|--force)
      FORCE_EXTRACT=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      log_error "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
  shift
done

# Execute requested operations
if [ "$DO_MENU" -eq 1 ]; then
  interactive_menu
else
  [ "$DO_VERIFY" -eq 1 ] && verify_payload
  [ "$DO_EXTRACT" -eq 1 ] && extract_payload
  [ "$DO_RUN" -eq 1 ] && run_bootstrap
fi

log_success "Done"
